.PHONY: clean All

All:
	@echo "----------Building project:[ zs4 - Debug ]----------"
	@$(MAKE) -f  "zs4.mk"
clean:
	@echo "----------Cleaning project:[ zs4 - Debug ]----------"
	@$(MAKE) -f  "zs4.mk" clean
